---
#### 2-2. 판다스 데이터 전처리 1 
---

In [1]:
#!pip install openpyxl
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns 
sns.set_theme(style='whitegrid')

In [2]:
coffee = pd.read_csv('coffee.csv', dtype={'price':float, 'cal':str})
coffee

        menu   price  cal
0  Americano  4500.0   10
1      Latte  5000.0  110
2       Moca  5500.0  250
3  Cappucino  5000.0  110
4   Espresso  4000.0   20
5    Milktea  5800.0  210
6   Greentea  5200.0    4

#### 자료형 변환

In [3]:
# 컬럼들의 자료형 확인 
coffee.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   menu    7 non-null      object
 1   price   7 non-null      float64
 2   cal     7 non-null      object
dtypes: float64(1), object(2)
memory usage: 296.0+ bytes

In [4]:
# price -> int, cal -> int로 변경 
coffee['price'] = coffee['price'].astype(int)
coffee['cal'] = coffee['cal'].astype(int)

coffee.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   menu    7 non-null      object
 1   price   7 non-null      int64
 2   cal     7 non-null      int64
dtypes: int64(2), object(1)
memory usage: 296.0+ bytes

#### 컬럼 추가

In [5]:
# new column
coffee['store'] = 'A-1'
coffee

        menu  price  cal store
0  Americano   4500   10   A-1
1      Latte   5000  110   A-1
2       Moca   5500  250   A-1
3  Cappucino   5000  110   A-1
4   Espresso   4000   20   A-1
5    Milktea   5800  210   A-1
6   Greentea   5200    4   A-1

In [6]:
# calculated columns 
coffee['discount_rate'] = 0.05
coffee['discount_price'] = (coffee['price']*( 1 - coffee['discount_rate'])).astype(int) 
coffee

        menu  price  cal store  discount_rate  discount_price
0  Americano   4500   10   A-1           0.05            4275
1      Latte   5000  110   A-1           0.05            4750
2       Moca   5500  250   A-1           0.05            5225
3  Cappucino   5000  110   A-1           0.05            4750
4   Espresso   4000   20   A-1           0.05            3800
5    Milktea   5800  210   A-1           0.05            5510
6   Greentea   5200    4   A-1           0.05            4940

In [7]:
# 행, 열 삭제 & store 정보 변경 
coffee_2 = coffee.drop(6, axis=0)
coffee_2 = coffee_2.drop(['discount_rate', 'discount_price'], axis=1)
coffee_2['store'] = 'A-2'
coffee_2

        menu  price  cal store
0  Americano   4500   10   A-2
1      Latte   5000  110   A-2
2       Moca   5500  250   A-2
3  Cappucino   5000  110   A-2
4   Espresso   4000   20   A-2
5    Milktea   5800  210   A-2

In [8]:
# loc 
coffee

        menu  price  cal store  discount_rate  discount_price
0  Americano   4500   10   A-1           0.05            4275
1      Latte   5000  110   A-1           0.05            4750
2       Moca   5500  250   A-1           0.05            5225
3  Cappucino   5000  110   A-1           0.05            4750
4   Espresso   4000   20   A-1           0.05            3800
5    Milktea   5800  210   A-1           0.05            5510
6   Greentea   5200    4   A-1           0.05            4940

In [9]:
print(coffee.loc[1,'price'])
print(coffee.iloc[1,1])

5000
5000

In [10]:
coffee.loc[2, 'menu':'cal'] 
coffee.loc[1:3, 'menu':'price'] 
coffee.iloc[:, 1:3] 
coffee.iloc[:, [0,3,5]]

        menu store  discount_price
0  Americano   A-1            4275
1      Latte   A-1            4750
2       Moca   A-1            5225
3  Cappucino   A-1            4750
4   Espresso   A-1            3800
5    Milktea   A-1            5510
6   Greentea   A-1            4940

In [11]:
print(coffee.loc[:3], '\n')
print(coffee.iloc[:3])

        menu  price  cal store  discount_rate  discount_price
0  Americano   4500   10   A-1           0.05            4275
1      Latte   5000  110   A-1           0.05            4750
2       Moca   5500  250   A-1           0.05            5225
3  Cappucino   5000  110   A-1           0.05            4750

        menu  price  cal store  discount_rate  discount_price
0  Americano   4500   10   A-1           0.05            4275
1      Latte   5000  110   A-1           0.05            4750
2       Moca   5500  250   A-1           0.05            5225

In [12]:
# 데이터 추가/변경 
coffee3 = coffee.copy()

## 1. origin 원산지 컬럼 추가하고, 값을 NaN으로 설정 
coffee3['origin'] = np.nan 

## 2. 일부 원산지 정보 추가 : 아메리카노 -> Nigiria, 모카/카푸치노 -> Brazil, 그린티 -> Korea 
coffee3.loc[0, 'origin'] = 'Nigiria'    # coffee4.iloc[0, 6] = 'Nigiria'
coffee3.loc[2:3, 'origin'] = 'Brazil'   # coffee4.iloc[2:4, 6] = 'Brazil'
coffee3.loc[6, 'origin'] = 'Korea'      # coffee4.iloc[6, 6] = 'Korea'

coffee3

/var/folders/26/vn1wz2xd3mj9r0sjzy_cj1jc0000gn/T/ipykernel_92922/1281761642.py:8: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Nigiria' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  coffee3.loc[0, 'origin'] = 'Nigiria'    # coffee4.iloc[0, 6] = 'Nigiria'

        menu  price  cal store  discount_rate  discount_price   origin
0  Americano   4500   10   A-1           0.05            4275  Nigiria
1      Latte   5000  110   A-1           0.05            4750      NaN
2       Moca   5500  250   A-1           0.05            5225   Brazil
3  Cappucino   5000  110   A-1           0.05            4750   Brazil
4   Espresso   4000   20   A-1           0.05            3800      NaN
5    Milktea   5800  210   A-1           0.05            5510      NaN
6   Greentea   5200    4   A-1           0.05            4940    Korea

In [13]:
## 인덱스의 역순으로 정렬 
coffee5 = coffee3.sort_index(ascending=False)     

## 가격의 오름차순 정렬  
coffee6 = coffee3.sort_values(by='price')

## 가격의 내림차순 + 원산지 낮은순으로 정렬 
coffee7 = coffee3.sort_values(by=['price', 'origin'], ascending=[False, True])
coffee7

        menu  price  cal store  discount_rate  discount_price   origin
5    Milktea   5800  210   A-1           0.05            5510      NaN
2       Moca   5500  250   A-1           0.05            5225   Brazil
6   Greentea   5200    4   A-1           0.05            4940    Korea
3  Cappucino   5000  110   A-1           0.05            4750   Brazil
1      Latte   5000  110   A-1           0.05            4750      NaN
0  Americano   4500   10   A-1           0.05            4275  Nigiria
4   Espresso   4000   20   A-1           0.05            3800      NaN

In [14]:
# new index (기존 인덱스는 삭제)
coffee7 = coffee7.reset_index(drop=True)

#### 필터링

In [15]:
coffee7

        menu  price  cal store  discount_rate  discount_price   origin
0    Milktea   5800  210   A-1           0.05            5510      NaN
1       Moca   5500  250   A-1           0.05            5225   Brazil
2   Greentea   5200    4   A-1           0.05            4940    Korea
3  Cappucino   5000  110   A-1           0.05            4750   Brazil
4      Latte   5000  110   A-1           0.05            4750      NaN
5  Americano   4500   10   A-1           0.05            4275  Nigiria
6   Espresso   4000   20   A-1           0.05            3800      NaN

In [16]:
# 원산지가 브리질인 것만 추출 
ans1 = coffee7[coffee7['origin'] == 'Brazil']

# 원산지가 브라질이 아닌 것만 추출 
ans2 = coffee7[coffee7['origin'] != 'Brazil']
## ans2 = coffee7[~(coffee7['origin'] == 'Brazil')]

# 원산지가 브라질 & 칼로리가 200 이하인 것만 추출 
ans3 = coffee7[
    (coffee7['origin'] == 'Brazil') & (coffee7['cal'] <= 200) 
]

# 원산지가 한국이거나 칼로리가 100 미만인 것만 추출 
ans4 = coffee7[
    (coffee7['origin'] == 'Korea') | (coffee7['cal'] < 100) 
]
# 메뉴명이 라떼인 것만 추출 
ans5 = coffee7[coffee7['menu'].isin(['Latte'])]

# 메뉴명에 알파벳 i가 들어간 것만 추출 
ans6 = coffee7[coffee7['menu'].str.contains('i')]

ans6

        menu  price  cal store  discount_rate  discount_price   origin
0    Milktea   5800  210   A-1           0.05            5510      NaN
3  Cappucino   5000  110   A-1           0.05            4750   Brazil
5  Americano   4500   10   A-1           0.05            4275  Nigiria

## 결측치

In [17]:
# 타이타닉 데이터 불러와 결측치 확인 
df = sns.load_dataset('titanic')
df.isnull()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
887,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
888,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False
889,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
890,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False

In [18]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [19]:
# age의 결측치를 평균나이로 대체 
df['age'] = df['age'].fillna(df['age'].mean())

# deck의 결측치를 최빈값으로 대체 
df['deck'] = df['deck'].fillna(df['deck'].mode()[0])

# embark_town 결측치는 해당 row를 삭제
df = df.dropna(subset=['embark_town'])   

# 결측치 정리 결과 확인 
df.isnull().sum()

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
deck           0
embark_town    0
alive          0
alone          0
dtype: int64

#### 특정값 변경

In [20]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,C,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,C,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,C,Southampton,no,True

In [21]:
# sex 컬럼의 male = 0, female = 1로 변경 
df2 = df.copy()

df2['sex'] = df2['sex'].replace('male', 0)
df2['sex'] = df2['sex'].replace('female', 1)

/var/folders/26/vn1wz2xd3mj9r0sjzy_cj1jc0000gn/T/ipykernel_92922/3711714214.py:5: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df2['sex'] = df2['sex'].replace('female', 1)

In [22]:
# map()으로 여러개의 값을 변경 
# class 컬럼의 값 변경 : First -> 1st, Second -> 2nd, Third -> 3rd 
class_map = {
    'First': '1st', 
    'Second': '2nd', 
    'Third': '3rd'
}

df3 = df.copy()
df3['class'] = df3['class'].map(class_map)

In [23]:
df4 = df.copy()
df4['class'] = df4['class'].replace(class_map)
df4.head()

/var/folders/26/vn1wz2xd3mj9r0sjzy_cj1jc0000gn/T/ipykernel_92922/3258820551.py:2: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df4['class'] = df4['class'].replace(class_map)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,3rd,man,True,C,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,1st,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,3rd,woman,False,C,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,1st,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,3rd,man,True,C,Southampton,no,True

#### 문자열 다루기

In [24]:
# 데이터 프레임 생성 
df = pd.DataFrame({
    'A': ['데이터 분석', '파이썬', '머신 러닝', 'AI'], 
    'B': [10,20,30,40], 
    'C': ['ab cd', 'AB CD', 'ef gh', 'IJ KL']
})
df

        A   B      C
0  데이터 분석  10  ab cd
1     파이썬  20  AB CD
2   머신 러닝  30  ef gh
3      AI  40  IJ KL

In [25]:
# replace(), str.replace()
df['B'] = df['B'].replace(10, 100)
df['A'] = df['A'].str.replace('분석', 'Analysis')

df

              A    B      C
0  데이터 Analysis  100  ab cd
1           파이썬   20  AB CD
2         머신 러닝   30  ef gh
3            AI   40  IJ KL

In [26]:
# split()
df['D'] = df['A'].str.split(' ')

display(df)
display(df['D'].str[0])

              A    B      C                D
0  데이터 Analysis  100  ab cd  [데이터, Analysis]
1           파이썬   20  AB CD            [파이썬]
2         머신 러닝   30  ef gh         [머신, 러닝]
3            AI   40  IJ KL             [AI]

0    데이터
1    파이썬
2     머신
3     AI
Name: D, dtype: object

In [27]:
# 대문자 변환 
df['C'] = df['C'].str.upper()

# 소문자 변환 
df['C'] = df['C'].str.lower()

# 공백제거 
df['C'] = df['C'].str.replace(' ', '')

# C 컬럼에 소문자 a가 포함된 데이터만 추출 
df_a = df[
    df['C'].str.contains('a')
]

#### groupby

In [28]:
# flights 데이터 로딩 
flights = sns.load_dataset('flights')
#flights

# 연도x월별 승긱수 합계, 평균, 최소, 최대
flights.groupby(['year', 'month'])['passengers'].sum()
flights.groupby(['year', 'month'])['passengers'].mean()
flights.groupby(['year', 'month'])['passengers'].max()
flights.groupby(['year', 'month'])['passengers'].min()

# agg() 사용 
flights.groupby(['year', 'month'])['passengers'].agg(['sum', 'mean', 'max', 'min'])

# new DataFrame (인덱스 초기화)
flights_new = flights.groupby(['year', 'month'])['passengers'].agg(['sum', 'mean', 'max', 'min']).reset_index()
flights_new

/var/folders/26/vn1wz2xd3mj9r0sjzy_cj1jc0000gn/T/ipykernel_92922/39529906.py:6: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  flights.groupby(['year', 'month'])['passengers'].sum()
/var/folders/26/vn1wz2xd3mj9r0sjzy_cj1jc0000gn/T/ipykernel_92922/39529906.py:7: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  flights.groupby(['year', 'month'])['passengers'].mean()
/var/folders/26/vn1wz2xd3mj9r0sjzy_cj1jc0000gn/T/ipykernel_92922/39529906.py:8: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  flights.groupby(['year', 'month'])['passengers'].max()
/var/folders/26/vn1wz2xd3mj9r0sjzy_cj1jc0000gn/T/ipykernel_92922/39529906.py:9: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  flights.groupby(['year', 'month'])['passengers'].min()
/var/folders/26/vn1wz2xd3mj9r0sjzy_cj1jc0000gn/T/ipykernel_92922/39529906.py:12: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  flights.groupby(['year', 'month'])['passengers'].agg(['sum', 'mean', 'max', 'min'])
/var/folders/26/vn1wz2xd3mj9r0sjzy_cj1jc0000gn/T/ipykernel_92922/39529906.py:15: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  flights_new = flights.groupby(['year', 'month'])['passengers'].agg(['sum', 'mean', 'max', 'min']).reset_index()

     year month  sum   mean  max  min
0    1949   Jan  112  112.0  112  112
1    1949   Feb  118  118.0  118  118
2    1949   Mar  132  132.0  132  132
3    1949   Apr  129  129.0  129  129
4    1949   May  121  121.0  121  121
..    ...   ...  ...    ...  ...  ...
139  1960   Aug  606  606.0  606  606
140  1960   Sep  508  508.0  508  508
141  1960   Oct  461  461.0  461  461
142  1960   Nov  390  390.0  390  390
143  1960   Dec  432  432.0  432  432

[144 rows x 6 columns]

In [29]:
# grouped
grouped = flights.groupby(['year', 'month'])['passengers'].mean()
grouped

/var/folders/26/vn1wz2xd3mj9r0sjzy_cj1jc0000gn/T/ipykernel_92922/3023225182.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  grouped = flights.groupby(['year', 'month'])['passengers'].mean()

year  month
1949  Jan      112.0
      Feb      118.0
      Mar      132.0
      Apr      129.0
      May      121.0
               ...
1960  Aug      606.0
      Sep      508.0
      Oct      461.0
      Nov      390.0
      Dec      432.0
Name: passengers, Length: 144, dtype: float64

In [30]:
# unstacked
grouped.unstack()

month,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec
year,,,,,,,,,,,,
1949,112.0,118.0,132.0,129.0,121.0,135.0,148.0,148.0,136.0,119.0,104.0,118.0
1950,115.0,126.0,141.0,135.0,125.0,149.0,170.0,170.0,158.0,133.0,114.0,140.0
1951,145.0,150.0,178.0,163.0,172.0,178.0,199.0,199.0,184.0,162.0,146.0,166.0
1952,171.0,180.0,193.0,181.0,183.0,218.0,230.0,242.0,209.0,191.0,172.0,194.0
1953,196.0,196.0,236.0,235.0,229.0,243.0,264.0,272.0,237.0,211.0,180.0,201.0
1954,204.0,188.0,235.0,227.0,234.0,264.0,302.0,293.0,259.0,229.0,203.0,229.0
1955,242.0,233.0,267.0,269.0,270.0,315.0,364.0,347.0,312.0,274.0,237.0,278.0
1956,284.0,277.0,317.0,313.0,318.0,374.0,413.0,405.0,355.0,306.0,271.0,306.0
1957,315.0,301.0,356.0,348.0,355.0,422.0,465.0,467.0,404.0,347.0,305.0,336.0
1958,340.0,318.0,362.0,348.0,363.0,435.0,491.0,505.0,404.0,359.0,310.0,337.0
1959,360.0,342.0,406.0,396.0,420.0,472.0,548.0,559.0,463.0,407.0,362.0,405.0
1960,417.0,391.0,419.0,461.0,472.0,535.0,622.0,606.0,508.0,461.0,390.0,432.0

#### transform

In [31]:
# 과일 데이터 로딩 
fruits = pd.read_csv('fruits.csv')
fruits

  fruits   price
0     딸기  1000.0
1   블루베리     NaN
2     딸기  1500.0
3   블루베리     NaN
4     딸기  2000.0
5   블루베리  2500.0
6     딸기     NaN
7   블루베리  1800.0

In [32]:
# groupby() vs transform()
print(fruits.groupby('fruits')['price'].mean(), '\n')
print(fruits.groupby('fruits')['price'].transform('mean'))

fruits
딸기      1500.0
블루베리    2150.0
Name: price, dtype: float64

0    1500.0
1    2150.0
2    1500.0
3    2150.0
4    1500.0
5    2150.0
6    1500.0
7    2150.0
Name: price, dtype: float64

In [33]:
# 결측값을 각 과일의 평균가격으로 대체 
avg_price = fruits.groupby('fruits')['price'].transform('mean')
fruits['price'] = fruits['price'].fillna(avg_price)
fruits

  fruits   price
0     딸기  1000.0
1   블루베리  2150.0
2     딸기  1500.0
3   블루베리  2150.0
4     딸기  2000.0
5   블루베리  2500.0
6     딸기  1500.0
7   블루베리  1800.0

#### 시계열 다루기

In [34]:
# 시계열 샘플 데이터 로딩 
df = pd.read_csv('datetime1.csv')
df.head(1).T

                                0
Date1                  2024-02-17
Date2                  2024:02:17
Date3                    24/02/17
Date4                  02/17/2024
Date5                 17-Feb-2024
DateTime1       24-02-17 13:45:30
DateTime2     2024-02-17 13-45-30
DateTime3  02/17/2024 01:45:30 PM
DateTime4    17 Feb 2024 13:45:30

In [35]:
# 날짜, 날짜/시간 데이터를 datetime 형태로 변경 
df['Date1'] = pd.to_datetime(df['Date1'])
df['Date2'] = pd.to_datetime(df['Date2'], format = '%Y:%m:%d')
df['Date3'] = pd.to_datetime(df['Date3'], format = '%y/%m/%d')
df['Date4'] = pd.to_datetime(df['Date4'], format = '%m/%d/%Y')
df['Date5'] = pd.to_datetime(df['Date5'])

df['DateTime1'] = pd.to_datetime(df['DateTime1'], format = '%y-%m-%d %H:%M:%S')
df['DateTime2'] = pd.to_datetime(df['DateTime2'], format = '%Y-%m-%d %H-%M-%S')
df['DateTime3'] = pd.to_datetime(df['DateTime3'], format = '%m/%d/%Y %I:%M:%S %p') #포맷 생략 가능 
df['DateTime4'] = pd.to_datetime(df['DateTime4'])

# 결과확인 
df.head(1).T

                            0
Date1     2024-02-17 00:00:00
Date2     2024-02-17 00:00:00
Date3     2024-02-17 00:00:00
Date4     2024-02-17 00:00:00
Date5     2024-02-17 00:00:00
DateTime1 2024-02-17 13:45:30
DateTime2 2024-02-17 13:45:30
DateTime3 2024-02-17 13:45:30
DateTime4 2024-02-17 13:45:30

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date1      4 non-null      datetime64[ns]
 1   Date2      4 non-null      datetime64[ns]
 2   Date3      4 non-null      datetime64[ns]
 3   Date4      4 non-null      datetime64[ns]
 4   Date5      4 non-null      datetime64[ns]
 5   DateTime1  4 non-null      datetime64[ns]
 6   DateTime2  4 non-null      datetime64[ns]
 7   DateTime3  4 non-null      datetime64[ns]
 8   DateTime4  4 non-null      datetime64[ns]
dtypes: datetime64[ns](9)
memory usage: 416.0 bytes

In [37]:
# datetime -> year, month, hour ... 
df['year'] = df['DateTime1'].dt.year
df['month'] = df['DateTime1'].dt.month
df['day'] = df['DateTime1'].dt.day
df['hour'] = df['DateTime1'].dt.hour
df['minute'] = df['DateTime1'].dt.minute
df['second'] = df['DateTime1'].dt.second

df['day_of_week'] = df['DateTime1'].dt.day_of_week
df['day_name'] = df['DateTime1'].dt.day_name()

# 결과 확인 
df.head(1).T

                               0
Date1        2024-02-17 00:00:00
Date2        2024-02-17 00:00:00
Date3        2024-02-17 00:00:00
Date4        2024-02-17 00:00:00
Date5        2024-02-17 00:00:00
DateTime1    2024-02-17 13:45:30
DateTime2    2024-02-17 13:45:30
DateTime3    2024-02-17 13:45:30
DateTime4    2024-02-17 13:45:30
year                        2024
month                          2
day                           17
hour                          13
minute                        45
second                        30
day_of_week                    5
day_name                Saturday

In [38]:
# datetime2 불러오기 
df2 = pd.read_csv('datetime2.csv')

# 연도-월 추출 
df2['yy_mm'] = df['DateTime4'].dt.to_period('M')
df2

             DateTime4    yy_mm
0  2024-02-17 13:45:00  2024-02
1  2024-02-18 14:55:00  2024-02
2  2024-02-19 15:30:00  2024-02
3  2024-02-20 16:10:00  2024-02

In [39]:
# 시간계산 
df2['+24hours'] = df['DateTime4'] + pd.Timedelta(hours=24)
df2['+100days'] = df['DateTime4'] + pd.Timedelta(days=100)
df2

             DateTime4    yy_mm            +24hours            +100days
0  2024-02-17 13:45:00  2024-02 2024-02-18 13:45:30 2024-05-27 13:45:30
1  2024-02-18 14:55:00  2024-02 2024-02-19 14:55:45 2024-05-28 14:55:45
2  2024-02-19 15:30:00  2024-02 2024-02-20 15:30:15 2024-05-29 15:30:15
3  2024-02-20 16:10:00  2024-02 2024-02-21 16:10:50 2024-05-30 16:10:50

In [40]:
# 지점별 평균 배달소요시간 계산 예제 
## 딜리버리타임 데이터 로딩, 컬럼 포맷을 datetime으로 변경 
df = pd.read_csv('delivery_time.csv')

df['order_time'] = pd.to_datetime(df['order_time'])
df['delivery_time'] = pd.to_datetime(df['delivery_time'])

## 각각의 배달소요시간 계산 (분 단위)
df['duration'] = (df['delivery_time'] - df['order_time']).dt.total_seconds() / 60 

## groupby()로 지점별 평균 배달소요시간 계산 
df.groupby('store')['duration'].mean()

store
A    25.000000
B    35.000000
C    36.666667
Name: duration, dtype: float64

#### 데이터 합치기

In [41]:
# menu1, menu2 데이터 불러오기 
menu1 = pd.read_csv('menu1.csv')
menu2 = pd.read_csv('menu2.csv')

display(menu1, menu2)

    Menu  Price
0  Salad   5000
1   Soup   3000
2  Bread   2000

      Menu  Price
0    Steak  15000
1    Pasta  12000
2  Chicken  10000

In [42]:
# 위-아래로 합치기 
full_menu = pd.concat([menu1, menu2], ignore_index=True)
full_menu

      Menu  Price
0    Salad   5000
1     Soup   3000
2    Bread   2000
3    Steak  15000
4    Pasta  12000
5  Chicken  10000

In [43]:
# 좌-우로 합치기 
full_menu2 = pd.concat([menu1, menu2], axis=1)
full_menu2

    Menu  Price     Menu  Price
0  Salad   5000    Steak  15000
1   Soup   3000    Pasta  12000
2  Bread   2000  Chicken  10000

In [45]:
# 할인정보 불러오기 
discount = pd.read_csv('discount_rate.csv')

# merge 
my_menu = pd.merge(full_menu, discount, on='Menu')
my_menu

      Menu  Price  discount_rate
0    Salad   5000           0.10
1     Soup   3000           0.15
2    Bread   2000           0.10
3    Steak  15000           0.20
4    Pasta  12000           0.15
5  Chicken  10000           0.20

#### 피벗 테이블

In [70]:
# pivot.csv 로딩 
table = pd.read_csv('pivot.csv')
table

   이름  부서  직급 성별  근속연수    급여
0  서아  개발  대리  여     3  3000
1  다인  기획  대리  여     5  3200
2  채아  개발  과장  남     4  3100
3  예담  기획  과장  여     6  3300
4  종현  개발  대리  남     7  3900
5  태헌  기획  차장  남     8  4000

In [75]:
# 부서별 평균급여 
df1 = table.pivot_table(
    index = '부서', 
    values = '급여',
    aggfunc = 'mean'
)

# 부서x직급별 급여 합계 
df2 = table.pivot_table(
    index= '부서', columns = '직급', values = '급여', aggfunc = 'sum'
)

# 부서&성별 x 직급별 평균 근속기간 
df3 = table.pivot_table(
    index = ['부서', '성별'], 
    columns = '직급', 
    values = ['근속연수', '급여'], 
    aggfunc = {'근속연수':'mean', '급여':'sum'}
)

df3

      근속연수                급여
직급      과장   대리   차장      과장      대리      차장
부서 성별
개발 남   4.0  7.0  NaN  3100.0  3900.0     NaN
   여   NaN  3.0  NaN     NaN  3000.0     NaN
기획 남   NaN  NaN  8.0     NaN     NaN  4000.0
   여   6.0  5.0  NaN  3300.0  3200.0     NaN