---
#### 2-3. 판다스 데이터 전처리 2
---

In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns 
sns.set_theme(style='whitegrid')

#### 빅분기 기출문제 풀이 #1 
- Data : https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch8/drinks.csv 
1. 대륙별 맥주소비량의 평균을 계산하고, 평균이 가장 큰 대륙을 찾아라
2. 위 대륙에서 맥주소비량(합계)이 5번째로 많은 국가의 맥주 소비량을 구하라

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch8/drinks.csv')
print(df.shape) 
df.head()

(193, 6)

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
0,Afghanistan,0,0,0,0.0,Asia
1,Albania,89,132,54,4.9,Europe
2,Algeria,25,0,14,0.7,Africa
3,Andorra,245,138,312,12.4,Europe
4,Angola,217,57,45,5.9,Africa

In [3]:
# 대륙별 맥주 소비량 평균 
ans1 = df.groupby('continent')['beer_servings'].mean()
ans1.sort_values(ascending=False)

continent
Europe           193.777778
South America    175.083333
North America    145.434783
Oceania           89.687500
Africa            61.471698
Asia              37.045455
Name: beer_servings, dtype: float64

In [4]:
# 유럽 대륙에서 국가별 맥주 소비량 구하기 
df_e = df[df['continent'] == 'Europe']
ans2 = df_e.groupby('country')['beer_servings'].sum()
ans2.sort_values(ascending=False)[:5]

country
Czech Republic    361
Germany           346
Lithuania         343
Poland            343
Ireland           313
Name: beer_servings, dtype: int64

#### 빅분기 기출문제 풀이 #2 
- Data : https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert_v2/main/part4/ch9/hr.csv 
1. 만족도 컬럼에 결측치가 존재한다. 전체 만족도의 평균값으로 대체하라. 
2. 근속연수의 결측치는 같은 부서내 동일한 성과등급을 가진 직원들의 평균 근속연수로 대체 
3. 각 직원의 연봉 / 근속연수 값을 계산, 그 값이 세번째로 큰 직원의 근속연수를 구하라
4. 각 직원의 연봉 / 만족도 값을 계산, 그 값이 두번째로 큰 직원의 교육 참가횟수를 구하라
5. 3과 4의 값을 더한 결과를 구하라 (정수출력)

In [5]:
df = pd.read_csv('https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert_v2/main/part4/ch9/hr.csv')
print(df.shape)
df.head()

(1000, 7)

    사원번호         부서 성과등급         연봉  근속연수  교육참가횟수  만족도
0  E0001  Marketing    B   73200000  14.0       5  6.0
1  E0002         IR    A   95100000   3.0       4  9.0
2  E0003    Manager    B   44700000   5.0       2  8.0
3  E0004         IR    B  122100000  16.0       3  8.0
4  E0005         IR    C   66000000   NaN       4  8.0

In [6]:
# 결측치 확인 
df.isnull().sum()

사원번호        0
부서          0
성과등급        0
연봉          0
근속연수       48
교육참가횟수      0
만족도       120
dtype: int64

In [7]:
# 만족도 결측치 대체 
df['만족도'] = df['만족도'].fillna(df['만족도'].mean())

# 근속연수 결측치 대체 
res1 = df.groupby(['부서','성과등급'])['근속연수'].transform('mean')
df['근속연수'] = df['근속연수'].fillna(res1)

# 결과확인 
df.isnull().sum()

사원번호      0
부서        0
성과등급      0
연봉        0
근속연수      0
교육참가횟수    0
만족도       0
dtype: int64

In [8]:
# 연봉/근속연수 계산 
df['ratio1'] = df['연봉']/df['근속연수'] 
df.sort_values(by='ratio1', ascending=False)

# 연봉/만족도 계산 
df['ratio2'] = df['연봉']/df['만족도'] 
df.sort_values(by='ratio2', ascending=False)

,사원번호,부서,성과등급,연봉,근속연수,교육참가횟수,만족도,ratio1,ratio2
490,E0491,Finance,B,149000000,13.000000,6,1.0,1.146154e+07,1.490000e+08
737,E0738,HR,A,146200000,9.000000,6,1.0,1.624444e+07,1.462000e+08
408,E0409,Finance,B,146100000,6.000000,3,1.0,2.435000e+07,1.461000e+08
575,E0576,Sales,B,144500000,9.433962,1,1.0,1.531700e+07,1.445000e+08
975,E0976,Manager,C,142500000,11.000000,3,1.0,1.295455e+07,1.425000e+08
...,...,...,...,...,...,...,...,...,...
235,E0236,Finance,A,46800000,12.000000,1,9.0,3.900000e+06,5.200000e+06
847,E0848,HR,A,41000000,19.000000,6,8.0,2.157895e+06,5.125000e+06
827,E0828,Manager,A,45300000,18.000000,1,9.0,2.516667e+06,5.033333e+06
929,E0930,Sales,C,40000000,11.032258,6,8.0,3.625731e+06,5.000000e+06
199,E0200,Finance,A,43600000,4.000000,2,9.0,1.090000e+07,4.844444e+06

---

In [9]:
# data
df = pd.read_csv('data/type1_data1.csv')
df

        id   age city    f1  f2      f3    f4         f5  subscribed   views
0     id01   2.0   서울   NaN   0    gold  ENFJ  91.297791  2024-07-16  6820.0
1     id02   9.0   서울  70.0   1     NaN  ENFJ  60.339826  2024-05-12  2534.0
2     id03  27.0   서울  61.0   1    gold  ISTJ  17.252986  2024-03-16  7312.0
3     id04  75.0   서울   NaN   2     NaN  INFP  52.667078  2024-07-21   493.0
4     id05  24.0   서울  85.0   2     NaN  ISFJ  29.269869  2024-03-07  1338.0
..     ...   ...  ...   ...  ..     ...   ...        ...         ...     ...
115  id114  22.0   대구  23.0   0    gold  INTP   0.000000  2025-02-17  9747.0
116  id115  23.0   부산  65.0   0     vip  ENTP   0.000000  2025-02-17  5628.0
117  id116  23.0   서울  12.0   1  silver  INFP   0.000000  2025-02-17  1267.0
118  id117  23.0   대구  65.0   2    gold  INFP   0.000000  2025-02-17  6543.0
119  id118  24.0   부산  94.0   1     vip  ESFJ   0.000000  2025-02-17  2356.0

[120 rows x 10 columns]

In [10]:
#Q1. filtering 
df = pd.read_csv('data/type1_data1.csv')

df = df[df['f5'] != 0] 
df['views'] = df['views'].fillna(df['views'].min())
print('views 컬럼의 중앙값 = ', df['views'].median().astype(int))

views 컬럼의 중앙값 =  5924

In [11]:
#Q2. slicing 
df = pd.read_csv('data/type1_data1.csv')

ans = df['subscribed'].mode()[0]
int(ans[-2:])

17

In [12]:
#Q3. new columns
df = pd.read_csv('data/type1_data1.csv')

df = df.dropna()
df['views_2'] = df['views'] / df['f1']
df.sort_values(by='views_2', ascending = False).head(1)

,id,age,city,f1,f2,f3,f4,f5,subscribed,views,views_2
115,id114,22.0,대구,23.0,0,gold,INTP,0.0,2025-02-17,9747.0,423.782609

In [13]:
#Q4. fillna()
df = pd.read_csv('data/type1_data1.csv')

df['views'] = df['views'].fillna(0)
tmp = df.sort_values(by='views', ascending=False).head(10)
print(tmp, '\n')

print(tmp['views'].sum())

        id   age city    f1  f2      f3    f4         f5  subscribed    views
5     id06  22.0   서울  57.0   0     vip  INTP  20.129444  2024-09-12  21550.0
56    id56  59.0   대구   NaN   1     vip  ESTJ  73.586397  2024-04-05  19589.0
83    id83  73.0   경기  50.0   1     vip  ENTP  80.138280  2024-09-26  19139.0
32    id32  25.0   부산  64.0   0     vip  ISFJ  13.049921  2024-05-24  17421.0
100  id100  47.0   경기  53.0   0     vip  ESFP  33.308999  2024-02-21  15535.0
10   id100  47.0   경기  53.0   0     vip  ESFP  33.308999  2024-02-21  15535.0
104  id103  21.0   부산  53.0   0     vip  ISFP   0.000000  2025-02-17  13543.0
114  id113  22.0   경기  34.0   2  silver  ENTP   0.000000  2025-02-17  10346.0
9     id10  95.0   서울  74.0   1    gold  ISFP  98.429899  2024-04-03   9992.0
113  id112  22.0   서울  45.0   2     vip  ENTP   0.000000  2025-02-17   9877.0

152527.0

In [14]:
#Q5. str()
df = pd.read_csv('data/type1_data1.csv')

df = df[df['f4'].str.contains('FJ')]
round(df['f2'].mean(), 2)

np.float64(0.61)

In [15]:
#Q6. calc
df = pd.read_csv('data/type1_data1.csv')

df['age'] = df['age']+1
df_20 = df[(df['age']>=20) & (df['age']<30)]
df_30 = df[(df['age']>=30) & (df['age']<40)]

abs(df_20['views'].mean() - df_30['views'].mean())

np.float64(263.13076923076915)

In [16]:
#Q7. dt
df = pd.read_csv('data/type1_data1.csv')

print(df['subscribed'].info())
df['subscribed'] = pd.to_datetime(df['subscribed'])
print(df['subscribed'].info())

df['yy_mm'] = df['subscribed'].dt.to_period('M')
df = df[df['yy_mm'] == '2024-02']
df[df['f3'] == 'gold'].shape

<class 'pandas.core.series.Series'>
RangeIndex: 120 entries, 0 to 119
Series name: subscribed
Non-Null Count  Dtype
--------------  -----
120 non-null    object
dtypes: object(1)
memory usage: 1.1+ KB
None
<class 'pandas.core.series.Series'>
RangeIndex: 120 entries, 0 to 119
Series name: subscribed
Non-Null Count  Dtype
--------------  -----
120 non-null    datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 1.1 KB
None

(5, 11)

In [17]:
#Q8. groupby()
df = pd.read_csv('data/type1_data1.csv')

df = df.dropna()
df.groupby('city').mean(numeric_only=True).sort_values(by='f2', ascending=False)

            age         f1        f2         f5        views
city
서울    38.000000  60.142857  0.785714  41.122705  7369.142857
경기    48.704000  61.360000  0.760000  52.106731  8127.880000
부산    35.075000  65.875000  0.687500  38.638715  6945.437500
대구    49.773333  66.200000  0.666667  27.370166  6819.133333

In [18]:
#Q9. quantile()
df = pd.read_csv('data/type1_data1.csv')

df = df.dropna()
print(df.shape)

df = df[:int(len(df)*0.7)]
print(df.shape)

abs(df['views'].quantile(0.75) - df['views'].quantile(0.25))

(70, 10)
(49, 10)

np.float64(2771.0)

In [19]:
#Q10. nan
df = pd.read_csv('data/type1_data1.csv')

print(df.isnull().sum())
df = df.dropna(subset=['f1'])
df['f3'] = df['f3'].fillna(df['f3'].mode()[0])

print(df.isnull().sum())

id             0
age            0
city           0
f1            31
f2             0
f3            29
f4             0
f5             0
subscribed     0
views          4
dtype: int64
id            0
age           0
city          0
f1            0
f2            0
f3            0
f4            0
f5            0
subscribed    0
views         2
dtype: int64

In [20]:
#Q11. replace(), map()
df = pd.read_csv('data/type1_data1.csv')

print(df['f3'].isnull().sum())
print(df['f3'].value_counts())

mapping = {
    np.nan : 0, 'silver':1, 'gold':2, 'vip':3
}

df['f3'] = df['f3'].replace(mapping)
print(df['f3'].value_counts())

'''
## map()
df['f3'] = df['f3'].map(mapping)
print(df['f3'].value_counts())
'''

df['f3'].sum()

29
f3
gold      57
silver    22
vip       12
Name: count, dtype: int64
f3
2    57
0    29
1    22
3    12
Name: count, dtype: int64

/var/folders/26/vn1wz2xd3mj9r0sjzy_cj1jc0000gn/T/ipykernel_3426/2356258893.py:11: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['f3'] = df['f3'].replace(mapping)

np.int64(172)

In [21]:
#Q12. dtypes
df = pd.read_csv('data/type1_data1.csv')

print(df.info())
num_cols = df.select_dtypes(exclude='object').columns 
# num_cols = df.select_dtypes(include=['int64','float64']).columns 

df = df[num_cols].fillna(0)
sum(df.sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          120 non-null    object
 1   age         120 non-null    float64
 2   city        120 non-null    object
 3   f1          89 non-null     float64
 4   f2          120 non-null    int64
 5   f3          91 non-null     object
 6   f4          120 non-null    object
 7   f5          120 non-null    float64
 8   subscribed  120 non-null    object
 9   views       116 non-null    float64
dtypes: float64(4), int64(1), object(5)
memory usage: 9.5+ KB
None

723597.949046703

In [22]:
#Q13. outlier
df = pd.read_csv('data/type1_data1.csv')

iqr = df['views'].quantile(0.75) - df['views'].quantile(0.25)
upper_lim = df['views'].quantile(0.75) + 1.5*iqr
lower_lim = df['views'].quantile(0.25) - 1.5*iqr

df = df[
    (df['views'] <= lower_lim) | (df['views'] >= upper_lim)
]

df['views'].sum()

np.float64(77699.0)

In [23]:
#Q14. backfill
df = pd.read_csv('data/type1_data1.csv')

print(df.isnull().sum())
df = df.bfill()  #df = df.fillna(method='bfill')
print(df.isnull().sum())

df.groupby(['city','f2']).sum(numeric_only=True)

id             0
age            0
city           0
f1            31
f2             0
f3            29
f4             0
f5             0
subscribed     0
views          4
dtype: int64
id            0
age           0
city          0
f1            0
f2            0
f3            0
f4            0
f5            0
subscribed    0
views         0
dtype: int64

            age      f1           f5     views
city f2
경기   0   1192.9  1490.0  1425.236647  154066.0
     1    997.0  1016.0   935.958628   91442.0
     2    296.0   390.0   430.186433   42709.0
대구   0    664.0   982.0   371.184620  100421.0
     1    393.6   471.0   404.779978   49536.0
     2    185.0   321.0    79.667919   22624.0
부산   0    525.0   691.0   395.272907   80460.0
     1    475.7   684.0   460.657406   51624.0
     2     38.5   189.0   101.195372   17771.0
서울   0    241.0   480.0   484.809540   61447.0
     1    433.3   687.0   506.371383   59111.0
     2    165.3   337.0   179.328213   22405.0

In [24]:
#Q15. dt.month
df = pd.read_csv('data/type1_data1.csv')

print(df['subscribed'].info())
df['subscribed'] = pd.to_datetime(df['subscribed'])
print(df['subscribed'].info())

df['month'] = df['subscribed'].dt.month
#df.head()

df.groupby('month').sum(numeric_only=True).sort_values(by='views')

<class 'pandas.core.series.Series'>
RangeIndex: 120 entries, 0 to 119
Series name: subscribed
Non-Null Count  Dtype
--------------  -----
120 non-null    object
dtypes: object(1)
memory usage: 1.1+ KB
None
<class 'pandas.core.series.Series'>
RangeIndex: 120 entries, 0 to 119
Series name: subscribed
Non-Null Count  Dtype
--------------  -----
120 non-null    datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 1.1 KB
None

         age      f1  f2          f5     views
month
11     186.0   181.0   1  278.410220   15857.0
12     365.0   373.0   2  515.672397   28658.0
6      481.8   244.0   6  387.206296   31295.0
3      326.3   457.0   8  352.729057   39031.0
1      441.8   608.0   1  487.453162   40013.0
4      307.0   268.0   4  312.187975   41307.0
10     483.0   437.0   6  595.737639   48705.0
8      338.5   119.0   6  520.223827   51048.0
9      473.6   356.0   3  379.121958   66340.0
7      534.0   399.0  10  630.370464   67677.0
5      809.6   822.0  10  855.287894  110786.0
2      860.7  1301.0  25  460.248156  165852.0

In [ ]:
#Q16. late order
df = pd.read_csv('data/delivery_time.csv')
#print(df.info())
display(df.head())

df['주문시간'] = pd.to_datetime(df['주문시간'])
df['실제도착시간'] = pd.to_datetime(df['실제도착시간'])
df['예상도착시간'] = pd.to_datetime(df['예상도착시간'])
#print(df.info())

df = df[
    df['예상도착시간'] > df['실제도착시간']
]
print('지연배달(건) = ', len(df))

df = df[
    df['거리'] >= 7
]
print('지연배달 중 거리 7km 이상(건) = ', len(df))

,주문시간,실제도착시간,예상도착시간,앱종류,거리,결제종류,user
0,2023-07-26 08:05:49,2023-07-26 09:14:06,2023-07-26 08:39:42,여기여,1.93,카드,user_275
1,2022-11-07 10:21:54,2022-11-07 10:44:04,2022-11-07 10:50:15,배고팡,5.19,카드,user_360
2,2023-04-18 05:00:57,2023-04-18 06:12:46,2023-04-18 05:32:53,배고팡,13.85,카드,user_36
3,2023-08-18 10:46:28,2023-08-18 11:16:25,2023-08-18 11:08:33,배고팡,10.90,앱결제,user_65
4,2023-08-11 09:58:27,2023-08-11 11:27:57,2023-08-11 10:51:57,여기여,14.96,카드,user_176

지연배달(건) =  490
지연배달 중 거리 7km 이상(건) =  318

In [ ]:
#Q17. late order
df = pd.read_csv('data/delivery_time.csv')
#print(df.info())
display(df.head())

df['주문시간'] = pd.to_datetime(df['주문시간'])
df['실제도착시간'] = pd.to_datetime(df['실제도착시간'])
df['예상도착시간'] = pd.to_datetime(df['예상도착시간'])
#print(df.info())

df['소요시간'] = (df['실제도착시간'] - df['주문시간']).dt.total_seconds() / 60 
print(df.groupby('앱종류')['소요시간'].mean())

df['배달지연'] = df['예상도착시간'] > df['실제도착시간']
print('\n', df.groupby('앱종류')['배달지연'].mean())

,주문시간,실제도착시간,예상도착시간,앱종류,거리,결제종류,user
0,2023-07-26 08:05:49,2023-07-26 09:14:06,2023-07-26 08:39:42,여기여,1.93,카드,user_275
1,2022-11-07 10:21:54,2022-11-07 10:44:04,2022-11-07 10:50:15,배고팡,5.19,카드,user_360
2,2023-04-18 05:00:57,2023-04-18 06:12:46,2023-04-18 05:32:53,배고팡,13.85,카드,user_36
3,2023-08-18 10:46:28,2023-08-18 11:16:25,2023-08-18 11:08:33,배고팡,10.90,앱결제,user_65
4,2023-08-11 09:58:27,2023-08-11 11:27:57,2023-08-11 10:51:57,여기여,14.96,카드,user_176

앱종류
배고팡    61.818694
배달왕    63.517864
여기여    62.343110
Name: 소요시간, dtype: float64

 앱종류
배고팡    0.519288
배달왕    0.464072
여기여    0.486322
Name: 배달지연, dtype: float64

In [ ]:
#Q18. interval 
df = pd.read_csv('data/delivery_time.csv')
#print(df.info())
display(df.head())

df['주문시간'] = pd.to_datetime(df['주문시간'])
df['실제도착시간'] = pd.to_datetime(df['실제도착시간'])
df['예상도착시간'] = pd.to_datetime(df['예상도착시간'])
#print(df.info())

first_order = df.groupby('user')['주문시간'].min()
last_order = df.groupby('user')['주문시간'].max()
interval = (last_order - first_order).dt.days
interval = interval[interval > 0]

print('고객별 이용기간 = ', interval)
print('\n', '평균이용기간 = ', interval.mean())
print('\n', '평균보다 이용기간이 긴 고객수 = ', len(interval[interval > interval.mean()]))

,주문시간,실제도착시간,예상도착시간,앱종류,거리,결제종류,user
0,2023-07-26 08:05:49,2023-07-26 09:14:06,2023-07-26 08:39:42,여기여,1.93,카드,user_275
1,2022-11-07 10:21:54,2022-11-07 10:44:04,2022-11-07 10:50:15,배고팡,5.19,카드,user_360
2,2023-04-18 05:00:57,2023-04-18 06:12:46,2023-04-18 05:32:53,배고팡,13.85,카드,user_36
3,2023-08-18 10:46:28,2023-08-18 11:16:25,2023-08-18 11:08:33,배고팡,10.90,앱결제,user_65
4,2023-08-11 09:58:27,2023-08-11 11:27:57,2023-08-11 10:51:57,여기여,14.96,카드,user_176

고객별 이용기간 =  user
user_1      149
user_10     283
user_105    230
user_106    307
user_107    291
           ...
user_89     158
user_9      170
user_91     128
user_93     103
user_95     121
Name: 주문시간, Length: 298, dtype: int64

 평균이용기간 =  167.69463087248323

 평균보다 이용기간이 긴 고객수 =  146

In [ ]:
#Q19. max order
df = pd.read_csv('data/delivery_time.csv')
#print(df.info())
display(df.head())

df['주문시간'] = pd.to_datetime(df['주문시간'])
df['실제도착시간'] = pd.to_datetime(df['실제도착시간'])
df['예상도착시간'] = pd.to_datetime(df['예상도착시간'])
#print(df.info())

df['yy_mm'] = df['주문시간'].dt.to_period('M')
md = df.groupby('yy_mm').count().sort_values(by='주문시간', ascending=False)
print('주문최다일 = ', md.index[0])

df = df[df['yy_mm'] == '2022-09']
df['결제종류'].value_counts(normalize = True)

,주문시간,실제도착시간,예상도착시간,앱종류,거리,결제종류,user
0,2023-07-26 08:05:49,2023-07-26 09:14:06,2023-07-26 08:39:42,여기여,1.93,카드,user_275
1,2022-11-07 10:21:54,2022-11-07 10:44:04,2022-11-07 10:50:15,배고팡,5.19,카드,user_360
2,2023-04-18 05:00:57,2023-04-18 06:12:46,2023-04-18 05:32:53,배고팡,13.85,카드,user_36
3,2023-08-18 10:46:28,2023-08-18 11:16:25,2023-08-18 11:08:33,배고팡,10.90,앱결제,user_65
4,2023-08-11 09:58:27,2023-08-11 11:27:57,2023-08-11 10:51:57,여기여,14.96,카드,user_176

주문최다일 =  2022-09

결제종류
앱결제    0.347368
현금     0.336842
카드     0.315789
Name: proportion, dtype: float64

In [99]:
#Q20. launch time
df = pd.read_csv('data/delivery_time.csv')
#print(df.info())
display(df.head())
print('전체주문건 =', len(df))

df['주문시간'] = pd.to_datetime(df['주문시간'])
df['실제도착시간'] = pd.to_datetime(df['실제도착시간'])
df['예상도착시간'] = pd.to_datetime(df['예상도착시간'])
#print(df.info())

df = df[
    (df['주문시간'].dt.hour >= 10) & (df['주문시간'].dt.hour <=13)
]
print('점심주문건 = ', len(df))

df['소요시간'] = (df['실제도착시간'] - df['주문시간']).dt.total_seconds() / 3600
df['배달속도'] = df['거리'] / df['소요시간']
df['과속'] = df['배달속도'] > 40

print('점심시간 과속 건수 = ', df['과속'].sum())

,주문시간,실제도착시간,예상도착시간,앱종류,거리,결제종류,user
0,2023-07-26 08:05:49,2023-07-26 09:14:06,2023-07-26 08:39:42,여기여,1.93,카드,user_275
1,2022-11-07 10:21:54,2022-11-07 10:44:04,2022-11-07 10:50:15,배고팡,5.19,카드,user_360
2,2023-04-18 05:00:57,2023-04-18 06:12:46,2023-04-18 05:32:53,배고팡,13.85,카드,user_36
3,2023-08-18 10:46:28,2023-08-18 11:16:25,2023-08-18 11:08:33,배고팡,10.90,앱결제,user_65
4,2023-08-11 09:58:27,2023-08-11 11:27:57,2023-08-11 10:51:57,여기여,14.96,카드,user_176

전체주문건 = 1000
점심주문건 =  154
점심시간 과속 건수 =  5

In [101]:
#Q21. delivery fee
df = pd.read_csv('data/delivery_time.csv')
#print(df.info())
display(df.head())

df['주문시간'] = pd.to_datetime(df['주문시간'])
df['실제도착시간'] = pd.to_datetime(df['실제도착시간'])
df['예상도착시간'] = pd.to_datetime(df['예상도착시간'])
#print(df.info())

def d_fee(x): 
    if x < 5 : 
        return 2000
    elif x < 10: 
        return 4000 
    elif x < 15: 
        return 6000
    else: 
        return 8000

df['배달료'] = df['거리'].apply(d_fee)    

df['yy_mm'] = df['주문시간'].dt.to_period('M')
df.groupby('yy_mm')['배달료'].sum()

,주문시간,실제도착시간,예상도착시간,앱종류,거리,결제종류,user
0,2023-07-26 08:05:49,2023-07-26 09:14:06,2023-07-26 08:39:42,여기여,1.93,카드,user_275
1,2022-11-07 10:21:54,2022-11-07 10:44:04,2022-11-07 10:50:15,배고팡,5.19,카드,user_360
2,2023-04-18 05:00:57,2023-04-18 06:12:46,2023-04-18 05:32:53,배고팡,13.85,카드,user_36
3,2023-08-18 10:46:28,2023-08-18 11:16:25,2023-08-18 11:08:33,배고팡,10.90,앱결제,user_65
4,2023-08-11 09:58:27,2023-08-11 11:27:57,2023-08-11 10:51:57,여기여,14.96,카드,user_176

yy_mm
2022-08    152000
2022-09    446000
2022-10    388000
2022-11    384000
2022-12    442000
2023-01    386000
2023-02    340000
2023-03    408000
2023-04    410000
2023-05    420000
2023-06    448000
2023-07    434000
2023-08    292000
Freq: M, Name: 배달료, dtype: int64

In [112]:
#Q22. weekend
df = pd.read_csv('data/delivery_time.csv')
#print(df.info())
display(df.head())

df['주문시간'] = pd.to_datetime(df['주문시간'])
df['실제도착시간'] = pd.to_datetime(df['실제도착시간'])
df['예상도착시간'] = pd.to_datetime(df['예상도착시간'])
#print(df.info())

df['dayofweek'] = df['주문시간'].dt.dayofweek
df_weekday = df[df['dayofweek'] < 5]
df_weekend = df[df['dayofweek'] >= 5]

print('주중 일평균 배달건수 = ', df_weekday['주문시간'].count() / df_weekday['주문시간'].dt.date.nunique()) 
print('주말 일평균 배달건수 = ', df_weekend['주문시간'].count() / df_weekend['주문시간'].dt.date.nunique())

,주문시간,실제도착시간,예상도착시간,앱종류,거리,결제종류,user
0,2023-07-26 08:05:49,2023-07-26 09:14:06,2023-07-26 08:39:42,여기여,1.93,카드,user_275
1,2022-11-07 10:21:54,2022-11-07 10:44:04,2022-11-07 10:50:15,배고팡,5.19,카드,user_360
2,2023-04-18 05:00:57,2023-04-18 06:12:46,2023-04-18 05:32:53,배고팡,13.85,카드,user_36
3,2023-08-18 10:46:28,2023-08-18 11:16:25,2023-08-18 11:08:33,배고팡,10.90,앱결제,user_65
4,2023-08-11 09:58:27,2023-08-11 11:27:57,2023-08-11 10:51:57,여기여,14.96,카드,user_176

주중 일평균 배달건수 =  2.869918699186992
주말 일평균 배달건수 =  3.094736842105263

In [120]:
#Q23. Top10
df = pd.read_csv('data/school_data.csv')
df.head()

df['avg_score'] = (df[['수학','영어','국어']].sum(axis=1)) / 3
#df['avg_score'] = (df['수학'] + df['영어'] + df['국어'])/3
df = df.sort_values(by='avg_score')[:10]
df

     이름  수학  영어  국어 수학교사 영어교사 국어교사  avg_score
14  코알라  25   3  56  박선생  장선생  이선생  28.000000
27  펠리칸  66  30   3  김선생  유선생  이선생  33.000000
2    토끼  98   7   6  김선생  장선생  최선생  37.000000
21  두더지  49  22  44  김선생  유선생  최선생  38.333333
29    매  47  70  11  김선생  유선생  이선생  42.666667
17    뱀  36  75  18  김선생  장선생  이선생  43.000000
20   하마  68  10  51  박선생  유선생  이선생  43.000000
3    사자  17  99  14  김선생  유선생  최선생  43.333333
9    판다  47  27  58  박선생  장선생  이선생  44.000000
19  침팬지  80  58   1  박선생  장선생  이선생  46.333333

In [131]:
#Q24. merge
df = pd.read_csv('data/school_data.csv')
df1 = pd.read_csv('data/school_data_science.csv')
df2 = pd.read_csv('data/school_data_social.csv')

df_all = pd.merge(df, df1, on='이름')
df_all = pd.merge(df_all, df2, on='이름')
display(df_all.head())

col_order = ['이름','수학','영어','국어','과학','사회','수학교사','영어교사','국어교사','과학교사','사회교사']
df_all = df_all[col_order]
display(df_all.head())

df_all['avg_score'] = (df_all[['수학','영어','국어','과학','사회']].sum(axis=1)) / 5
display(df_all.head())

    이름  수학  영어  국어 수학교사 영어교사 국어교사  과학 과학교사  사회 사회교사
0  강아지  66  61  26  김선생  장선생  최선생  66  황선생  58  오선생
1  고양이  92  48  80  김선생  장선생  이선생  92  임선생  10  오선생
2   토끼  98   7   6  김선생  장선생  최선생  98  황선생  30  오선생
3   사자  17  99  14  김선생  유선생  최선생  17  임선생  97  우선생
4  호랑이  83  92  75  박선생  장선생  이선생  83  임선생  34  오선생

    이름  수학  영어  국어  과학  사회 수학교사 영어교사 국어교사 과학교사 사회교사
0  강아지  66  61  26  66  58  김선생  장선생  최선생  황선생  오선생
1  고양이  92  48  80  92  10  김선생  장선생  이선생  임선생  오선생
2   토끼  98   7   6  98  30  김선생  장선생  최선생  황선생  오선생
3   사자  17  99  14  17  97  김선생  유선생  최선생  임선생  우선생
4  호랑이  83  92  75  83  34  박선생  장선생  이선생  임선생  오선생

    이름  수학  영어  국어  과학  사회 수학교사 영어교사 국어교사 과학교사 사회교사  avg_score
0  강아지  66  61  26  66  58  김선생  장선생  최선생  황선생  오선생       55.4
1  고양이  92  48  80  92  10  김선생  장선생  이선생  임선생  오선생       64.4
2   토끼  98   7   6  98  30  김선생  장선생  최선생  황선생  오선생       47.8
3   사자  17  99  14  17  97  김선생  유선생  최선생  임선생  우선생       48.8
4  호랑이  83  92  75  83  34  박선생  장선생  이선생  임선생  오선생       73.4

In [ ]:
#Q25. transform
df = pd.read_csv('data/sales.csv')
display(df)

df['평균판매금액(지역별)'] = df.groupby('지역코드')['판매금액'].transform('mean')
df['판매금액'] = df['판매금액'].fillna(df['평균판매금액(지역별)'])
df

    지역코드  거래ID    판매금액
0    101  T001  1000.0
1    101  T002  1200.0
2    101  T003     NaN
3    101  T004  1500.0
4    101  T005  1100.0
5    102  T006  2000.0
6    102  T007  2500.0
7    102  T008  2300.0
8    102  T009     NaN
9    102  T010  2100.0
10   103  T011  3000.0
11   103  T012  3500.0
12   103  T013  3200.0
13   103  T014  4000.0
14   103  T015     NaN

    지역코드  거래ID    판매금액  평균판매금액(지역별)
0    101  T001  1000.0       1200.0
1    101  T002  1200.0       1200.0
2    101  T003  1200.0       1200.0
3    101  T004  1500.0       1200.0
4    101  T005  1100.0       1200.0
5    102  T006  2000.0       2225.0
6    102  T007  2500.0       2225.0
7    102  T008  2300.0       2225.0
8    102  T009  2225.0       2225.0
9    102  T010  2100.0       2225.0
10   103  T011  3000.0       3425.0
11   103  T012  3500.0       3425.0
12   103  T013  3200.0       3425.0
13   103  T014  4000.0       3425.0
14   103  T015  3425.0       3425.0

In [150]:
#Q26. pivot 
df = pd.read_csv('data/region_sales.csv')
display(df.head())

table = pd.pivot_table(
    df, 
    index = ['Region', 'Channel'], 
    columns = ['Product'], 
    values = 'Sales', 
    aggfunc = 'sum'
)
display(table)

table['SUM'] = table['A'] + table['B']
table

         Date Region Product  Channel  Sales
0  2025-01-05  North       A   Online    120
1  2025-01-07  South       A  Offline    150
2  2025-02-10  North       B   Online    200
3  2023-02-12  North       A   Online    130
4  2025-03-15   East       A  Offline    100

Product           A    B
Region Channel
East   Offline  100  105
       Online   205  210
North  Offline  140  180
       Online   440  420
South  Offline  150  145
       Online   160  170
West   Offline  110  115
       Online   135  130

Product           A    B  SUM
Region Channel
East   Offline  100  105  205
       Online   205  210  415
North  Offline  140  180  320
       Online   440  420  860
South  Offline  150  145  295
       Online   160  170  330
West   Offline  110  115  225
       Online   135  130  265

In [156]:
df = pd.read_csv('data/monthly_sales.csv')
display(df.head())

df_new = pd.melt(
    df, 
    id_vars = 'Region', 
    value_vars = ['Jan', 'Feb', 'Mar'], 
    var_name = 'Month', 
    value_name = 'Sales'
)

display(df_new)

df_new.groupby(['Region','Month'])['Sales'].sum().reset_index()

  Region  Jan  Feb  Mar
0  Seoul  120  135  110
1  Seoul   95  108  145
2  Seoul  200  179  140
3  Seoul  150  155  170
4  Seoul  110   98  190

      Region Month  Sales
0      Seoul   Jan    120
1      Seoul   Jan     95
2      Seoul   Jan    200
3      Seoul   Jan    150
4      Seoul   Jan    110
..       ...   ...    ...
145  Daejeon   Mar    170
146  Daejeon   Mar    115
147  Daejeon   Mar    140
148  Daejeon   Mar    105
149  Daejeon   Mar    175

[150 rows x 3 columns]

     Region Month  Sales
0     Busan   Feb   1323
1     Busan   Jan   1256
2     Busan   Mar   1371
3     Daegu   Feb   1365
4     Daegu   Jan   1317
5     Daegu   Mar   1538
6   Daejeon   Feb   1348
7   Daejeon   Jan   1350
8   Daejeon   Mar   1400
9   Incheon   Feb   1444
10  Incheon   Jan   1436
11  Incheon   Mar   1466
12    Seoul   Feb   1425
13    Seoul   Jan   1385
14    Seoul   Mar   1420